# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  app:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2
      - name: Run CI
      - run: yarn ci
      - name: Build and install deps
      - run: yarn run build
      - name: Prettier
      - run: yarn prettier-check
      - name: ESLint
      - run: yarn lint
      - name: Jest
      - run: yarn test
